# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b5727ef8694f76df02ec3a69fc385b3058d73809a60f8adefc16b0ed9843df1bc7a10f13bacb09bb7794763c6dfd4365c813e55014b1292e5b472c4717a82f6

test:
  secret_key_base: b2f7c99320d3973c9c90e75df34b61410a90c3512d41b7cafcff48820ab3404ebae6df0f80f2b5d92fc2b0cf2d6469e4e10181541e4050b737e1fce465512eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
